# SPDX-License-Identifier: MPL-2.0
CPMAddPackage(NAME chronon URL "${CHRONON_ARCHIVE}" URL_HASH "SHA256=${CHRONON_ARCHIVE_HASH}"
    OPTIONS "CHRONON_BUILD_TESTS OFF" "CHRONON_BUILD_BENCHMARKS OFF" "CHRONON_INSTALL OFF")
