import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Core Framework',
      items: [
        'guides/architecture',
        'guides/units-and-simulation',
        'guides/port-system',
        'guides/pipeline-registers',
        'guides/versioned-register',
        'guides/priority-arbiter',
        'guides/scheduling',
      ],
    },
    {
      type: 'category',
      label: 'Observability',
      items: [
        'guides/observability',
        'guides/counters',
        'guides/scheduler-timeline',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'guides/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'guides/mpsc-atomic-publish',
        'guides/stage-registers',
        'guides/broadcast-bus',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        'guides/simulator-comparison',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'guides/performance',
        'guides/faq',
        'guides/changelog',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
